# Generated by Django 5.0 on 2023-12-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_answers_comment_alter_answers_score'),
        ('teachers', '0005_exam_pass_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_answers', to='teachers.question')),
            ],
        ),
    ]
