# Generated by Django 5.0 on 2023-12-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mc', 'multiple choice'), ('essay', 'Open Questions')], default='mc', max_length=20),
            preserve_default=False,
        ),
    ]
