# Generated by Django 5.0 on 2023-12-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_exam_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
