# Generated by Django 5.0 on 2023-12-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_option_is_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_code',
            field=models.CharField(default='code', max_length=100),
            preserve_default=False,
        ),
    ]
