# Generated by Django 5.0 on 2023-12-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student',
            field=models.EmailField(max_length=254),
        ),
    ]
